# Generated by Django 2.1.1 on 2018-10-08 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_quiz',
            name='ClassID',
        ),
        migrations.RemoveField(
            model_name='class_quiz',
            name='QuizID',
        ),
        migrations.RemoveField(
            model_name='student_quiz',
            name='Quiz',
        ),
        migrations.RemoveField(
            model_name='student_quiz',
            name='Student',
        ),
        migrations.DeleteModel(
            name='Class_Quiz',
        ),
        migrations.DeleteModel(
            name='Student_Quiz',
        ),
    ]
