# Generated by Django 2.1.1 on 2018-10-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='QuestionText',
        ),
    ]
