# Generated by Django 2.1.1 on 2018-09-12 04:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20180911_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Class')),
            ],
            options={
                'verbose_name_plural': 'teachers',
                'db_table': 'Teachers',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='Public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Teacher'),
        ),
    ]
