# Generated by Django 2.1.1 on 2018-09-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20180912_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
    ]
