# Generated by Django 2.1.1 on 2018-09-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20180912_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='ClassID',
            field=models.TextField(),
        ),
    ]
